### ISSUE TITLE
500 error after updating

### ISSUE THREAD

**Issue by gimmickyboot** [linuxserver/ifai#1351]
HI all.

After updating from v2.5.6 to v2.6.1 I'm getting an http 500 error with the following in the apache error log.

> PHP Fatal error:  Uncaught ReflectionException: Class "view" does not exist in /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php:912\nStack trace:\n#0 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(912): ReflectionClass->__construct()\n#1 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()\n#2 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(957): Illuminate\\Container\\Container->resolve()\n#3 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()\n#4 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(942): Illuminate\\Container\\Container->make()\n#5 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(1454): Illuminate\\Foundation\\Application->make()\n#6 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Container\\Container->offsetGet()\n#7 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance()\n#8 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(349): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()\n#9 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(16): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#10 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(744): Illuminate\\Foundation\\Exceptions\\RegisterErrorViewPaths->__invoke()\n#11 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(719): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()\n#12 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(650): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()\n#13 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(556): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()\n#14 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(473): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()\n#15 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(218): Illuminate\\Foundation\\Exceptions\\Handler->render()\n#16 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(195): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#17 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#18 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#19 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#20 {main}\n\nNext Illuminate\\Contracts\\Container\\BindingResolutionException: Target class [view] does not exist. in /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php:914\nStack trace:\n#0 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()\n#1 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(957): Illuminate\\Container\\Container->resolve()\n#2 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()\n#3 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(942): Illuminate\\Container\\Container->make()\n#4 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(1454): Illuminate\\Foundation\\Application->make()\n#5 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Container\\Container->offsetGet()\n#6 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance()\n#7 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(349): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()\n#8 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(16): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#9 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(744): Illuminate\\Foundation\\Exceptions\\RegisterErrorViewPaths->__invoke()\n#10 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(719): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()\n#11 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(650): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()\n#12 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(556): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()\n#13 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(473): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()\n#14 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(218): Illuminate\\Foundation\\Exceptions\\Handler->render()\n#15 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(195): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#16 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#17 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#18 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#19 {main}\n  thrown in /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 914

I'm updating as follows...
```
cd /tmp
curl -L "https://github.com/linuxserver/Heimdall/archive/refs/tags/v2.6.1.zip" -o Heimdall-2.6.1.zip
unzip Heimdall-2.6.1.zip
cp -R Heimdall-2.6.1/* /usr/local/Heimdall/
chown -R www-data /usr/local/Heimdall
```

If I clone to a new dir then there's no issue so it's something to do with the update.

Any ideas on what the issue is?

Cheers,
Shannon

**Comment by rrosson** [comment]
This issue still happens after pulling the latest docker image as of today 8/2/2024

**Comment by klugerama** [comment]
I'm also getting this, but it doesn't seem to matter if it's a new directory or the existing directory. Possibly because I'm using mysql.

**Comment by gimmickyboot** [comment]
I just tried to update to 2.6.2 using the above commands and I'm still getting a 500 error. Error from apache2 error log

`[Tue Nov 05 18:17:19.434917 2024] [php:error] [pid 3493660:tid 3493660] [client 172.16.100.11:59276] PHP Fatal error:  Uncaught ReflectionException: Class "view" does not exist in /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php:912\nStack trace:\n#0 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(912): ReflectionClass->__construct()\n#1 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()\n#2 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(957): Illuminate\\Container\\Container->resolve()\n#3 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()\n#4 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(942): Illuminate\\Container\\Container->make()\n#5 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(1454): Illuminate\\Foundation\\Application->make()\n#6 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Container\\Container->offsetGet()\n#7 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance()\n#8 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(349): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()\n#9 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(16): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#10 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(744): Illuminate\\Foundation\\Exceptions\\RegisterErrorViewPaths->__invoke()\n#11 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(719): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()\n#12 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(650): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()\n#13 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(556): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()\n#14 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(473): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()\n#15 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(218): Illuminate\\Foundation\\Exceptions\\Handler->render()\n#16 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(195): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#17 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#18 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#19 {main}\n\nNext Illuminate\\Contracts\\Container\\BindingResolutionException: Target class [view] does not exist. in /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php:914\nStack trace:\n#0 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()\n#1 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(957): Illuminate\\Container\\Container->resolve()\n#2 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()\n#3 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(942): Illuminate\\Container\\Container->make()\n#4 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(1454): Illuminate\\Foundation\\Application->make()\n#5 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Container\\Container->offsetGet()\n#6 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance()\n#7 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(349): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()\n#8 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(16): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#9 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(744): Illuminate\\Foundation\\Exceptions\\RegisterErrorViewPaths->__invoke()\n#10 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(719): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()\n#11 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(650): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()\n#12 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(556): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()\n#13 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(473): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()\n#14 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(218): Illuminate\\Foundation\\Exceptions\\Handler->render()\n#15 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(195): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#16 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#17 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#18 {main}\n  thrown in /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 914
[Tue Nov 05 18:17:19.435151 2024] [php:error] [pid 3493660:tid 3493660] [client 172.16.100.11:59276] PHP Fatal error:  Uncaught ReflectionException: Class "view" does not exist in /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php:912\nStack trace:\n#0 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(912): ReflectionClass->__construct()\n#1 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()\n#2 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(957): Illuminate\\Container\\Container->resolve()\n#3 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()\n#4 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(942): Illuminate\\Container\\Container->make()\n#5 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(1454): Illuminate\\Foundation\\Application->make()\n#6 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Container\\Container->offsetGet()\n#7 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance()\n#8 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(349): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()\n#9 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(16): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#10 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(744): Illuminate\\Foundation\\Exceptions\\RegisterErrorViewPaths->__invoke()\n#11 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(719): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()\n#12 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(650): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()\n#13 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(556): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()\n#14 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(473): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()\n#15 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(218): Illuminate\\Foundation\\Exceptions\\Handler->render()\n#16 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(195): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#17 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#18 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#19 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#20 {main}\n\nNext Illuminate\\Contracts\\Container\\BindingResolutionException: Target class [view] does not exist. in /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php:914\nStack trace:\n#0 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(795): Illuminate\\Container\\Container->build()\n#1 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(957): Illuminate\\Container\\Container->resolve()\n#2 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(731): Illuminate\\Foundation\\Application->resolve()\n#3 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Application.php(942): Illuminate\\Container\\Container->make()\n#4 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php(1454): Illuminate\\Foundation\\Application->make()\n#5 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(237): Illuminate\\Container\\Container->offsetGet()\n#6 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(208): Illuminate\\Support\\Facades\\Facade::resolveFacadeInstance()\n#7 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Support/Facades/Facade.php(349): Illuminate\\Support\\Facades\\Facade::getFacadeRoot()\n#8 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/RegisterErrorViewPaths.php(16): Illuminate\\Support\\Facades\\Facade::__callStatic()\n#9 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(744): Illuminate\\Foundation\\Exceptions\\RegisterErrorViewPaths->__invoke()\n#10 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(719): Illuminate\\Foundation\\Exceptions\\Handler->registerErrorViewPaths()\n#11 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(650): Illuminate\\Foundation\\Exceptions\\Handler->renderHttpException()\n#12 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(556): Illuminate\\Foundation\\Exceptions\\Handler->prepareResponse()\n#13 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Exceptions/Handler.php(473): Illuminate\\Foundation\\Exceptions\\Handler->renderExceptionResponse()\n#14 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(218): Illuminate\\Foundation\\Exceptions\\Handler->render()\n#15 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(195): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->renderHttpResponse()\n#16 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(231): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleException()\n#17 /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Foundation/Bootstrap/HandleExceptions.php(255): Illuminate\\Foundation\\Bootstrap\\HandleExceptions->handleShutdown()\n#18 [internal function]: Illuminate\\Foundation\\Bootstrap\\HandleExceptions->Illuminate\\Foundation\\Bootstrap\\{closure}()\n#19 {main}\n  thrown in /usr/local/Heimdall/vendor/laravel/framework/src/Illuminate/Container/Container.php on line 914`

**Comment by KodeStar** [comment]
Have you tried creating it from scratch and copying the database over? My guess is there is some conflicting files from the old install. 2.6.0 updated the underlying Laravel version from 8 to 10

**Comment by gimmickyboot** [comment]
That seems to have done the trick. Settings are reporting v2.6.3.

I only copied over the database dir and .env file. If there's anything else I should bring over let me know
